# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HO-I76U0Nkvxixjc7dm-7nx6TNm78Wkj
"""

import numpy as np

rango = range(1,11)
np_diez_numeros=np.array(rango)
np_diez_numeros

np_diez_numeros[7]

np_diez_numeros[-3]

ajedrez_64=np.arange(1,65).reshape(8,8)
ajedrez_64

array_100=np.arange(1,101).reshape(10,10)
array_100

array_100.sum()

split_arrays = np.vsplit(array_100, [5])
sum_part1 = np.sum(split_arrays[0])
sum_part2 = np.sum(split_arrays[1])
print("Sum of first part:", sum_part1)
print("Sum of second part:", sum_part2)

array_50=np.vsplit(array_100,[5])
array_50

array_50a,array_50b=array_50
array_50a

array_50a.sum()  #suma de toda la matriz

array_100.mean()   #promedio de toda la matriz

array_100.max()   #Valor maximo de toda la matriz

np.median(array_100)  #Mediana de toda la matriz

np.std(array_100)   #Variacion estandar de toda la matriz

np.var(array_100) #Varianza de toda la matriz